### ISSUE TITLE
Merge fails

### ISSUE THREAD

**Issue by dpisarenko** [jcabi/jcabi-beanstalk-maven-plugin#14]
Merge of https://github.com/jcabi/jcabi-beanstalk-maven-plugin/issues/2 fails due to reasons I don't understand.

Full log: http://www.rultor.com/t/1723-71196385

Please make sure that the issue above can be merged.

**Comment by yegor256** [comment]
@dmarkov assign me to this, I'll fix

**Comment by dmarkov** [comment]
we'll find someone to do this task, soon

**Comment by dmarkov** [comment]
@dpisarenko many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `50663267`

**Comment by dmarkov** [comment]
> @dmarkov assign me to this, I'll fix

@yegor256 the task is yours, please proceed

**Comment by yegor256** [comment]
@dpisarenko I believe it's fixed already, please check and close

**Comment by dmarkov** [comment]
@yegor256 **30 mins** sent to your balance (ID `000-349201b0`), many thanks!. +30 added to your rating, current score is: [+5483](http://www.netbout.com/b/35008?open=rating)
