### ISSUE TITLE
WarFile.java:134-135: Implement validation of YAML inside...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-beanstalk-maven-plugin#15]
Puzzle `2-c30faef8` in `src/main/java/com/jcabi/beanstalk/maven/plugin/WarFile.java:134-135` has to be resolved: Implement validation of YAML inside the method AbstractBeanstalkMojo.validYaml. Remember to unit test your solution.... The puzzle was created by Dmitri Pisarenko on 22-Jan-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmarkov** [comment]
@maurezen the task is yours please proceed

**Comment by maurezen** [comment]
@dmarkov please assign this to another developer.

**Comment by maurezen** [comment]
@dmarkov @yegor256 any comments?

**Comment by yegor256** [comment]
@dmarkov let's assign this to someone else pls

**Comment by dmarkov** [comment]
> @dmarkov let's assign this to someone else pls

@yegor256 I'll ask somebody else to pick this up

**Comment by dmarkov** [comment]
@nhekfqn the issue is yours, please help

**Comment by dmarkov** [comment]
@marcuss please go ahead with this task, it's yours

**Comment by dmarkov** [comment]
@marcuss you're working with this ticket for the last 15 days. If it is not closed within the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck... do not forget that you should remove the `@todo` puzzle from the source code... added -30 to your rating, now it is equal to [-60](http://www.netbout.com/b/35292?open=rating)

**Comment by dmarkov** [comment]
@tmjee please go ahead, it's your task now, keep [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions you may have

Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by tmjee** [comment]
@dmarkov Any reason why validation has to be done in AbstractBeanstalkMojo.validYaml instead of WarFile?

**Comment by tmjee** [comment]
@dmarkov  created #26, which might be related to this as well.

**Comment by tmjee** [comment]
@dmarkov probably want to fix #27  first? or else I'll need jdk7 which i haven't got installed now

**Comment by tmjee** [comment]
@dmarkov fixed in #28

**Comment by dmarkov** [comment]
> @dmarkov Any reason why validation has to be done in AbstractBeanstalkMojo.validYaml instead of WarFile? Json validation is being done in WarFile, it seems weird to spread out the validation 

@tmjee try to avoid asking technical questions in the ticket. if something is not clear, it's a bug in the project, see http://www.yegor256.com/2015/01/15/how-to-cut-corners.html

**Comment by dmarkov** [comment]
> @dmarkov  created #26, which might be related to this as well. 

@tmjee OK thanks

**Comment by dmarkov** [comment]
> @dmarkov probably want to fix #27  first? or else I'll need jdk7 which i haven't got installed now

@tmjee it's up to you

**Comment by tmjee** [comment]
@dmarkov Merged. Pls close issue. Thx

**Comment by dmarkov** [comment]
> @dmarkov Merged. Pls close issue. Thx

@tmjee sure, will do right after the next deployment cycle

**Comment by dmarkov** [comment]
@tmjee you're holding this task for 15 days already

do not forget that the ticket will be closed once the `@todo` puzzle is removed from the code, in master branch

added -30 to your rating, now it is equal to [+15](http://www.netbout.com/b/35603?open=rating)

**Comment by tmjee** [comment]
@dmarkov That's fine. removed @todo in pull request. Please do not assign any more issues to me.

**Comment by dmarkov** [comment]
> @dmarkov That's fine. removed @todo in pull request. Please do not assign any more issues to me. Thank you very much.

@tmjee sure, no problem. if you don't want any more tickets, post `@alice away` into Netbout

**Comment by dmarkov** [comment]
@yegor256 Closed, done, thanks all
