### ISSUE TITLE
WarFile.java:147-148: Implement validation of JSON inside...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-beanstalk-maven-plugin#16]
Puzzle `2-677fde75` in `src/main/java/com/jcabi/beanstalk/maven/plugin/WarFile.java:147-148` has to be resolved: Implement validation of JSON inside the method AbstractBeanstalkMojo.validJson(). Remember to unit test your solution.... The puzzle was created by Dmitri Pisarenko on 22-Jan-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmarkov** [comment]
@nhekfqn it's yours, please go ahead

**Comment by nhekfqn** [comment]
@dmarkov PR created https://github.com/jcabi/jcabi-beanstalk-maven-plugin/pull/18

**Comment by nhekfqn** [comment]
@dmarkov Related PR has been merged.

**Comment by nhekfqn** [comment]
@dmarkov can we please close the ticket?

**Comment by nhekfqn** [comment]
@dmarkov can you please close the ticket?

**Comment by dmarkov** [comment]
@nhekfqn this task is in your hands for 16 days already. do not forget that you should remove the `@todo` puzzle from the source code. added -30 to your rating, now it is equal to [+135](http://www.netbout.com/b/35123?open=rating)

**Comment by dmarkov** [comment]
once `16-a618f555` puzzle is resolved (later, in another ticket), this ticket will be fully complete

**Comment by nhekfqn** [comment]
@dmarkov 
> once 16-a618f555 puzzle is resolved (later, in another ticket), this ticket will be fully complete

Does that mean I need to wait for another ticket to be resolved to get the payment for this ticket?

**Comment by yegor256** [comment]
@nhekfqn nope, you are done here

**Comment by dmarkov** [comment]
The task is done, thanks all, I am closing it

**Comment by dmarkov** [comment]
@nhekfqn I added **30 mins** to your account, many thanks for working with the project!... +30 to your rating, your total score is [+180](http://www.netbout.com/b/35123?open=rating)

**Comment by dmarkov** [comment]
@yegor256 last puzzled solved `16-a618f555`/#21
