### ISSUE TITLE
validate ebextensions before deployment, for YAML validity

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-beanstalk-maven-plugin#2]
Moved from https://github.com/jcabi/jcabi/issues/109

Would be nice to validate `.ebextensions` directory in WAR package before deployment, for validity

**Comment by dmarkov** [comment]
@darkled just a reminder that you're working with this task for 13 days already

added -30 to your rating, now it is equal to [+45](http://www.netbout.com/b/35091?open=rating)

**Comment by darkled** [comment]
@dmarkov please, assign this task to someone else.

**Comment by dmarkov** [comment]
> @dmarkov please, assign this task to someone else.

@darkled OK, I will try to assign someone else

**Comment by dmarkov** [comment]
@dpisarenko the issue is yours, please help

**Comment by dpisarenko** [comment]
@yegor256 Is it correct that in scope of this task I need to implement something like

```
final File extdir = new File(".ebextensions");

for (final file : extdir.listFiles(new ConfigFileFilter())) {
	if (!(validYaml(file) || validJson(file))) {
		throw new Exception("File " + file.getAbsolutePath() 
		+ " is neither valid YAML, nor valid JSON");
	}
}
```
where `ConfigFileFilter` is defined as shown below?

```
public class ConfigFileFilter : FilenameFilter {
	public boolean accept(File dir, String name) {
		return name.endsWith(".config");
	}
}
```

**Comment by yegor256** [comment]
@dpisarenko I think they expect only YAML files there with `.config` extensions. We should validate that they are all in readable YAML format and they all end with `.config`

**Comment by yegor256** [comment]
@dpisarenko I may be wrong, please make sure you check the official documentation of AWS

**Comment by dpisarenko** [comment]
@yegor256 According to http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/customize-containers.html

> Configuration files should conform to YAML or JSON formatting standards

**Comment by yegor256** [comment]
@dpisarenko than you're right

**Comment by dpisarenko** [comment]
@yegor256 Is it correct that `.ebextensions` directory is supposed to be in the `com.jcabi.beanstalk.maven.plugin.AbstractBeanstalkMojo#war` archive?

**Comment by dpisarenko** [comment]
@yegor256 Is it OK, if

  1. I make sure that the method `com.jcabi.beanstalk.maven.plugin.AbstractBeanstalkMojo#checkEbextensionsValidity` runs inside a unit test and
  1. add TODOs for JSON and YAML validation?

```
private void checkEbextensionsValidity() throws MojoFailureException {
    try {
        final ZipFile warfile = createZipFile();
        final ZipEntry ebextdir = warfile.getEntry(".ebextensions");
        if (ebextdir == null)
            throw new MojoFailureException(
                ".ebextensions directory does not exist in the WAR file");
        final Enumeration<? extends ZipEntry> entries = warfile.entries();
        int files = 0;
        while (entries.hasMoreElements()) {
            final ZipEntry entry = entries.nextElement();
            if (entry.getName().startsWith(".ebextensions/")
                && !entry.isDirectory()) {
                files++;
                final String text = readFile(warfile, entry);
                if (!(validJson(text) || validYaml(text))) {
                    throw new MojoFailureException(Joiner.on("").join(
                        "File '",
                        entry.getName(),
                        "' in .ebextensions is neither valid JSON,",
                        " nor valid YAML"));
                }
            }
        }
    } catch (final IOException e) {
        Logger.error(this, e.getMessage());
        throw new MojoFailureException(".ebextensions validation failed");
    }
}

/**
 * Validates a YAML string.
 * @param text Text to validate
 * @return True, if text is a valid YAML string.
 * @todo #2:30min Implement validation of YAML inside the method
 * AbstractBeanstalkMojo.validYaml. Remember to unit test your solution.
 */
protected boolean validYaml(final String text) {
    throw new NotImplementedException(
        "com.jcabi.beanstalk.maven.plugin.AbstractBeanstalkMojo.validJson");
}

/**
 * Validates a JSON string.
 * @param text Text to validate
 * @return True, if text is a valid JSON string.
 * @todo #2:30min Implement validation of JSON inside the method
 * AbstractBeanstalkMojo.validJson(). Remember to unit test your solution.
 */
protected boolean validJson(final String text) {
    throw new NotImplementedException(
        "com.jcabi.beanstalk.maven.plugin.AbstractBeanstalkMojo.validJson");
}
```

**Comment by yegor256** [comment]
@dpisarenko looks good to me

**Comment by dpisarenko** [comment]
@yegor256 I created a test, which is supposed to verify that `execute` calls `checkEbextensionsValidity`. 

```
    @Test
    @Ignore
    public void executeCallscheckEbextensionsValidity()
        throws MojoFailureException {
        final AbstractBeanstalkMojo mojo = Mockito.spy(
            new AbstractBeanstalkMojoTest.BeanstalkMojoForTesting()
        );
        mojo.setSkip(false);
        Mockito.doNothing().when(mojo).checkEbextensionsValidity();
        mojo.execute();
        Mockito.verify(mojo).checkEbextensionsValidity();
    }
```

In order for it to run, I need to set the `war` member variable. How can I do it (set the `mojo.war` member variable inside the test), except using PowerMockito to set a private variable (which is considered a bad practice) ?

**Comment by dpisarenko** [comment]
@yegor256 How can I disable the `AbstractClassNameCheck` and `MultipleStringLiteralsCheck` checks for the `AbstractBeanstalkMojoTest` class?

I tried this:
```
/**
 * Tests for the AbstractBeanstalkMojo class.
 * @author Dmitri Pisarenko (dp@altruix.co)
 * @version $Id$
 * @since 1.0
 * @checkstyle AbstractClassNameCheck (1 lines)
 * @checkstyle MultipleStringLiteralsCheck (3 lines)
 */
public final class AbstractBeanstalkMojoTest {
```
but still get Checkstyle errors.

**Comment by yegor256** [comment]
@dpisarenko create a setter, like it's done with `setSkip()`

**Comment by yegor256** [comment]
@dpisarenko checkstyle is right in this case, don't test abstract classes. Instead, test concrete classes that extend them.

**Comment by dpisarenko** [comment]
@yegor256 Both `UpdateMojo` and `DeployMojo` (subclasses of `AbstractBeanstalkMojo`) are final, which means I cannot mock/spy on them with Mockito. What is the right way to do in this case?

**Comment by dpisarenko** [comment]
@yegor256 How can I disable Checkstyle's `MultipleStringLiteralsCheck`? I tried putting `@checkstyle MultipleStringLiteralsCheck (10 lines)` into the class Javadoc and `// @checkstyle MultipleStringLiteralsCheck (10 lines)` before the line, where the violation occurs, but none of that helped.

**Comment by yegor256** [comment]
put this one into the Javadoc of the class:

```
@checkstyle MultipleStringLiteralsCheck (500 lines)
```

should work

**Comment by dpisarenko** [comment]
@yegor256 The PR has been merged. Please close the issue. Thanks.

**Comment by yegor256** [comment]
@dpisarenko thanks!

**Comment by yegor256** [comment]
@rultor release, tag is `0.11`

**Comment by yegor256** [comment]
@rultor release, tag is `0.11`

**Comment by dmarkov** [comment]
these 2 puzzles were created in this ticket: `2-c30faef8`, `2-677fde75`

**Comment by dmarkov** [comment]
@dpisarenko thank you, added **30 mins** to your acc, payment num is `50842019`. +30 added to your rating, at the moment it is: [+551](http://www.netbout.com/b/35089?open=rating)

**Comment by dmarkov** [comment]
@yegor256 last 2 puzzles `2-c30faef8`/#15, `16-a618f555`/#21 originated from here were solved
