### ISSUE TITLE
Build failed on windows with lots of EOL violations

### ISSUE THREAD

**Issue by YamStranger** [jcabi/jcabi-beanstalk-maven-plugin#25]
@dmarkov Looks like we need to add .gitattributes to force EOL of the repo.

**Comment by dmarkov** [comment]
@yegor256 please dispatch this issue

**Comment by YamStranger** [comment]
@yegor256. It is known problem, qulice fail if default system EOF not like in linux. So we need add .attributes to repository for force setting Unix-like end of line to git repository. 
AppVeyor use linux like EOF. 
This repository will not build successfully if you install git, install maven, clone repo and just build. 
Here is some examples of same problem at different repositories:
This is issue same as here https://github.com/jcabi/jcabi-maven-skin/issues/24 (build failed on Windows)
same is here https://github.com/yegor256/takes/issues/148
fix mast be like here https://github.com/jcabi/jcabi-aether/pull/59/files#diff-fc723d30b02a4cca7a534518111c1a66 or like here https://github.com/jcabi/jcabi-dynamo/pull/43

**Comment by yegor256** [comment]
@YamStranger build is passing in appveyor

**Comment by YamStranger** [comment]
@yegor256 AppVeyor use linux like EOF for repositories by default for all git repo - it is system configuration.

**Comment by yegor256** [comment]
@YamStranger why can't you use the same?

**Comment by YamStranger** [comment]
@yegor256. Because it out of scope this repo. So you need add this in instructions - and this is issue too (it can be fix). 
Some repos already have such fixes -https://github.com/yegor256/thindeck/blob/master/.gitattributes, and some not - and it is a problem. It must be general rule, or fix for every repo or general instructions like SET JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8. 

Developers create issues like below not for fun, but because of problem:
yegor256/takes#148
jcabi/jcabi-maven-skin#24
https://github.com/jcabi/jcabi-dynamo/pull/43 (if is fix with reference to my issue)

**Comment by yegor256** [comment]
@YamStranger hm... so you're suggesting to add this `.gitattributes` file to all repos?

**Comment by YamStranger** [comment]
@yegor256 Yes. 
Because I remember near 5 issues with same idea (I cant find first, but I will if you ask):
"mvn clean install -DskipTests -Dinvoker.skip=true -Pqulice " fails, and reason - default EOF for windows systems.

**Comment by YamStranger** [comment]
@yegor256 Please reopen this issue and let's fix it. Build of repository should be successful when user follows all the  instructions in description. Now it is impossible, and user must guess what he needs to fix (it is not obviously) and spend a lot of time just for "clone and build".

**Comment by yegor256** [comment]
@YamStranger should be fixed now, see https://github.com/jcabi/jcabi-beanstalk-maven-plugin/commit/646c8cb28a33a95fcaaf2969073c536efce4207e

**Comment by YamStranger** [comment]
@yegor256 Now issue is fixed, so I can close it.

**Comment by yegor256** [comment]
@YamStranger it's closed already, thanks
