### ISSUE TITLE
Implement validation of JSON inside 

### ISSUE THREAD

**Issue by tmjee** [jcabi/jcabi-beanstalk-maven-plugin#26]
Referring to #15, if we moved YML validation to AbstractBeanstalkMojo, it makes sense to move the json validation there as well.

<hr id='w'>

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please

**Comment by yegor256** [comment]
@tmjee make sense, thanks

**Comment by dmarkov** [comment]
@tmjee many thanks for the report, I topped your account for 15 mins, transaction AP-8KG10328TX604722W

**Comment by dmarkov** [comment]
@prondzyn please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here; The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by prondzyn** [comment]
@dmarkov I prepared PR #30.

I also created a puzzle in [WarFile.java](https://github.com/prondzyn/jcabi-beanstalk-maven-plugin/blob/95e97ffbd7b09b1f2f8e0579912632fc93dfb1cd/src/main/java/com/jcabi/beanstalk/maven/plugin/WarFile.java#L54-L55) and I'm not sure if it will be processed automatically or should I create an issue for it?

**Comment by dmarkov** [comment]
> @dmarkov I prepared PR #30.
> 
> I also created a puzzle in [WarFile.java](https://github.com/prondzyn/jcabi-beanstalk-maven-plugin/blob/95e97ffbd7b09b1f2f8e0579912632fc93dfb1cd/src/main/java/com/jcabi/beanstalk/maven/plugin/WarFile.java#L54-L55) and I'm not sure if it will be processed automatically or should I create an issue for it?

@prondzyn the puzzle will be processed and converted to a ticket automatically, thanks

**Comment by prondzyn** [comment]
@dmarkov PR merged

**Comment by dmarkov** [comment]
@tmjee there is a puzzle in this code `26-1bde2abc`/#31, we'll resolve it later

**Comment by prondzyn** [comment]
@tmjee can you close the ticket, please?

**Comment by dmarkov** [comment]
> @dmarkov PR merged

@prondzyn thanks

**Comment by dmarkov** [comment]
@prondzyn **30 mins** was added to your account, many thanks for your contribution (payment AP-7G904156N8481390K)! The task took 266 hours and 34 mins.; +30 to your rating, your total score is [+75](http://www.netbout.com/b/35715?open=rating)

**Comment by dmarkov** [comment]
@tmjee the last puzzle `26-1bde2abc`/#31 originated from here solved
