### ISSUE TITLE
WarFile.java:51-52: Check and remove this class...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-beanstalk-maven-plugin#31]
Puzzle `26-1bde2abc` in `src/main/java/com/jcabi/beanstalk/maven/plugin/WarFile.java:51-52` has to be resolved: Check and remove this class as all the functionality is in AbstractBeanstalkMojo now.... The puzzle was created by Piotr Pradzynski on 15-Oct-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmarkov** [comment]
@nikoladespotoski please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here... The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by dmarkov** [comment]
@nikoladespotoski just a reminder that you're working with this task for 15 days already... do not forget that you should remove the `@todo` puzzle from the source code... -30 added to your rating, at the moment it is: [+310](http://www.netbout.com/b/36438?open=rating)

**Comment by NikolaDespotoski** [comment]
@dmarkov Assign someone else

**Comment by dmarkov** [comment]
> @dmarkov Assign someone else

@nikoladespotoski I will ask somebody else to pick this up

**Comment by dmarkov** [comment]
@piddubnyi the task is yours

**Comment by dmarkov** [comment]
@piddubnyi just a reminder that you're working with this task for 15 days already. do not forget that the ticket will be closed once the `@todo` puzzle is removed from the code, in master branch. -30 added to your rating, current score is: [+0](http://www.netbout.com/b/35966?open=rating)

**Comment by dmarkov** [comment]
@piddubnyi you've been working with this task for too long. I'm sorry, but I'll assign someone else. Please stop working with it. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. -60 added to your rating, current score is: [-120](http://www.netbout.com/b/35966?open=rating)

**Comment by dmarkov** [comment]
@westonized please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here... Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by westonized** [comment]
@dmarkov blocked by #36

**Comment by dmarkov** [comment]
> @dmarkov blocked by #36 

@westonized sure, we'll wait for #36

**Comment by westonized** [comment]
@dmarkov you can remove the block. It's still an issue, but appears unrelated to this one.

**Comment by dmarkov** [comment]
> @dmarkov you can remove the block. It's still an issue, but appears unrelated to this one.

@westonized it's OK, no worries, just finish this ticket and we'll close it

**Comment by westonized** [comment]
@dmarkov It is finished now as far as I'm convered, the related PR is merged.

**Comment by dmarkov** [comment]
> @dmarkov It is finished now as far as I'm concerned, the related PR is merged.

@westonized OK

**Comment by dmarkov** [comment]
@yegor256 I'm closing the issue...

**Comment by dmarkov** [comment]
@westonized Much obliged! I have added **30 mins** to your account in payment "AP-0C7380554S592190N", 215 hours and 33 mins spent. +30 to your rating, your total score is [+105](http://www.netbout.com/b/37035?open=rating)
