### ISSUE TITLE
OverridingBundle.java:109-110: Would be nice to make...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-beanstalk-maven-plugin#8]
Puzzle `103-6be90d8b` in `src/main/java/com/jcabi/beanstalk/maven/plugin/OverridingBundle.java:109-110` has to be resolved: Would be nice to make it cacheable, as suggested in https://github.com/yegor256/jcabi/issues/105

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by cyberone** [comment]
@dmarkov please review https://github.com/jcabi/jcabi-beanstalk-maven-plugin/pull/9

**Comment by cyberone** [comment]
@dmarkov the PR is merged and closed. You may close the issue.

**Comment by dmarkov** [comment]
Finished, thanks, closing..

**Comment by dmarkov** [comment]
@cyberone Thank you, I've added **30 mins** to your account in payment/transaction "`50214421`"; +30 to your rating, your total score is [-700](http://www.netbout.com/b/35076?open=rating)
